#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/kiosk-39c3-by-vincent:latest@sha256:028a239ad60d4477166ca9aaae4575232975d6c03b500a64a54dbf2a2d17859d
    restart: on-failure:5
    environment:
      - PORT=3011
    ports:
      - "3011:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
