#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/kiosk-39c3-by-vincent:latest@sha256:d75edecc1d6e4be83e2ffe276305d0feef276b2f8ac290331f8ae5fcab93aab9
    restart: on-failure:5
    environment:
      - PORT=3011
    ports:
      - "3011:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
