#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/kiosk-39c3-by-vincent:latest@sha256:dc343851577674a76ca6049f5bf7b3778fb27b720fb6f7cbcdff676edc8afa3e
    restart: on-failure:5
    environment:
      - PORT=3011
    ports:
      - "3011:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5
